
export const concerts = [
  {
    date: '05.09.2026',
    title: 'Koncert épatant',
    location: 'CHEZ PATEMMA',
    imageUrl: '/assets/images/concert-patemma.jpg',
  },
  {
    date: '15.05.2026',
    title: 'Didukipet',
    location: 'À LA POUILLADE',
    imageUrl: '/assets/images/concert-pouillade.jpg',
  },
  {
    date: '19.02.2026',
    title: 'Vachement bien !',
    location: 'AU PIANO VACHE',
    imageUrl: '/assets/images/concert-piano-vache.jpg',
  },
  {
    date: '17.01.2026',
    title: 'Apéro Koncert',
    location: 'CHEZ EMMA & DAVID',
    imageUrl: '/assets/images/concert-1.jpg',
  },
  {
    date: '21.06.2025',
    title: 'Koncert Perché',
    location: 'CHEZ CAC&RICO',
    imageUrl: '/assets/images/koncert-perche.jpg',
  },
  {
    date: '30.03.2025',
    title: 'Koncert Dominikal',
    location: 'CHEZ SONIA H',
    imageUrl: '/assets/images/concert-soniah.jpg',
  },
  {
    date: '24.05.2024',
    title: 'Koncert à la plage',
    location: 'CHEZ MARTINE',
    imageUrl: '/assets/images/concert-3.jpg',
  },
  {
    date: '13.05.2024',
    title: 'Koncert de la rose',
    location: 'CHEZ LEILA',
    imageUrl: '/assets/images/concert-leila.jpg',
  },
  {
    date: '15.02.2023',
    title: 'Koncert Ouvert',
    location: "À L'UTOPIA",
    imageUrl: '/assets/images/concert-utopia.jpg',
  },
  {
    date: '18.06.2022',
    title: 'Koncert étuvé',
    location: 'CHEZ PATEMMA',
    imageUrl: '/assets/images/concert-patemma-2022.jpg',
  },
  {
    date: '25.01.2020',
    title: 'Koncert alternatif',
    location: 'AU THEATRE DE VERRE',
    imageUrl: '/assets/images/concert-theatre-de-verre.jpg',
  },
  {
    date: '12.04.2019',
    title: 'Koncert barré',
    location: "AU BOMBY'S",
    imageUrl: '/assets/images/concert-bombys.jpg',
  },
  {
    date: '06.04.2019',
    title: 'Apéro-Koncert',
    location: 'CHEZ BARBALARIC',
    imageUrl: '/assets/images/concert-barbalaric.jpg',
  },
  {
    date: '02.12.2018',
    title: 'Apéro-Koncert',
    location: 'CHEZ FRED',
    imageUrl: '/assets/images/concert-goutte-dor.jpg',
  },
  {
    date: '09.06.2018',
    title: 'Keupon ki part, kimporte…',
    location: 'ANNI RIRI',
    imageUrl: '/assets/images/concert-anni-riri.jpg',
  },
];

export const galleryImages = [
    { src: '/assets/images/gallery-1.jpg', w: 2, h: 2 },
    { src: '/assets/images/gallery-11.jpg', w: 2, h: 2 },
    { src: '/assets/images/gallery-2.jpg', w: 1, h: 2 },
    { src: '/assets/images/gallery-3.jpg', w: 1, h: 1 },
    { src: '/assets/images/gallery-4.jpg', w: 1, h: 1 },
    { src: '/assets/images/gallery-12.jpg', w: 2, h: 2 },
    { src: '/assets/images/gallery-5.jpg', w: 1, h: 2 },
    { src: '/assets/images/gallery-6.jpg', w: 2, h: 2 },
    { src: '/assets/images/gallery-7.jpg', w: 1, h: 1 },
    { src: '/assets/images/gallery-13.jpg', w: 2, h: 2 },
    { src: '/assets/images/gallery-8.jpg', w: 1, h: 1 },
    { src: '/assets/images/gallery-9.jpg', w: 2, h: 1 },
    { src: '/assets/images/gallery-10.png', w: 2, h: 2 },
];

export const posters = [
  '/assets/images/poster-2026-05-15-pouillade.jpg',
  '/assets/images/poster-2026-02-19-piano-vache.jpg',
  '/assets/images/poster-2026-01-17.jpg',
  '/assets/images/poster-2025-06-21.jpg',
  '/assets/images/poster-2025-03-30.jpg',
  '/assets/images/poster-2024-05-24.jpg',
  '/assets/images/poster-2024-05-13.jpg',
  '/assets/images/poster-2023-10-14-sosofranso.jpg',
  '/assets/images/poster-2023-02-15.jpg',
  '/assets/images/poster-2022-06-18-patemma.jpg',
  '/assets/images/poster-2022-02-05.jpg',
  '/assets/images/poster-2020-01-26.jpg',
  '/assets/images/poster-2019-04-12.jpg',
  '/assets/images/poster-2019-04-06.jpg',
  '/assets/images/poster-2019-01-27.jpg',
];
